# Site info
site_tilte: 'Myles Braithwaite'
site_description: 'Hoping for the Best, Imagining the Worst.'
site_keywords:
  - Myles Braithwaite
  - Myles Alden Braithwaite
  - Myles
  - Braithwaite

url: https://mylesb.ca
baseurl: /

google_analytics: 'UA-1642439-32'

# Site structure
source: './source/'
destination: './build/'
uploads: './source/uploads/'
assets: './source/assets/'

# GnuPG stuff
gpg_short_id: '0x5B423590'
obsolete_gpg_short_id: '0x5A2FE7BF'
work_gpg_short_id: '0x7E0205AA'
bgi_gpg_short_id: '0x72C89F91'

# Deploy stuff
deploy:
  aws:
    bucket: 'mylesb.ca'

  stag:
    dest: '/srv/www/mylesb.ca/draft/html'
    host: 'myles@bear.mylesbraithwaite.com'
    port: 22

  prod:
    dest: '/srv/www/mylesb.ca/www/html'
    host: 'myles@bear.mylesbraithwaite.com'
    port: 22

  nfs:
    dest: '/home/public'
    host: 'myles_myles@ssh.phx.nearlyfreespeech.net'
    port: 22
